const Menu = [
    {
        id:1,
        image:"images/veggie.jpg",
        name:"veggie",
        category:"Breakfast",
        description:"A refreshing and tangy summer veggie wrap that’s easy to make and perfect for on the go – ideal for morning",
        price:'₹49',
    },
    {
        id:2,
        image:"images/Blueberry Baked Oatmeal.jpg",
        name:"Blueberry Baked Oatmeal",
        category:"Breakfast",
        description:"This baked oatmeal recipe is loaded with wholesome ingredients—oats, nuts, maple syrup and blueberries",
        price:'₹49',
    },{
        id:3,
        image:"images/Oats Masala Poha.jpg",
        name:"Oats Masala Poha",
        category:"Breakfast",
        description:"Oats poha or savory oats hash is a heart- healthy breakfast recipe, quick and simple enough for a busy morning",
        price:'₹49',
    },{
        id:4,
        image:"images/Loaded Vegetable Sandwich.jpg",
        name:"Loaded Vegetable Sandwich",
        category:"Lunch",
        description:"This sandwich has the perfect balance of savory, crunchy, fatty and a hint of spicy from the pickled jalapeño!",
        price:'₹49',
    },{
        id:5,
        image:"images/Chicken burrito bowl.jpg",
        name:"Chicken burrito bowl",
        category:"Lunch",
        description:"This fabulous minced chicken is cooked with oyster sauce, soya sauce, basil and seasoned lightly for beautiful flavors",
        price:'₹49',
    },{
        id:6,
        image:"images/Pasta salad.jpg",
        name:"Pasta salad",
        category:"Lunch",
        description:"This slurpy curry pasta is the real deal. Boiled pasta is cooked in a decadent puree of tomatoes and meat masala and served in 20 minutes.",
        price:'₹49',
    },{
        id:7,
        image:"images/Oriental Basil Chicken.jpg",
        name:"Oriental Basil Chicken",
        category:"Dinner",
        description:"Thai Basil Chicken is arguably the gold standard of Thai Chicken stir fries! An incredibly fast and easy Thai recipe",
        price:'₹49',
    },{
        id:8,
        image:"images/Tomato Paneer.jpg",
        name:"Tomato Paneer",
        category:"Dinner",
        description:"Cottage cheese chunks, tomato puree, a pinch of sugar and mild spices tossed in olive oil is also a low fat dinner alternative. This one's a vegetarian's delight.",
        price:'₹49',
    },{
        id:9,
        image:"images/Scrambled Eggs with Chicken Sausages.jpg",
        name:"Scrambled Eggs with Chicken Sausages",
        category:"Dinner",
        description:"A simple lip smacking plate of scrambled eggs and fried chicken sausages drizzled with olive oil. These are amazing delights, we promise.",
        price:'₹49',
    },{
        id:10,
        image:"images/LOW-FAT GREEK YOGURT AND FRUIT.jpg",
        name:"Low-Fat Greek Yogurt & Fruit",
        category:"Night-Cravings",
        description:"We already know that Greek yogurt is a great source of protein, but we had no idea that it could help us catch some ZZZs, too.",
        price:'₹49',
    },
    {
        id:11,
        image:"images/PEANUT BUTTER AND JELLY SANDWICH.jpg",
        name:"Peanut Butter & Jelly Sandwich",
        category:"Night-Cravings",
        description:"Who knew our childhood favorite was actually a prime midnight snack? Here’s why: According to survey, peanut butter is a natural source of protein",
        price:'₹49',
    },
    {
        id:12,
        image:"images/BANANAS AND PEANUT BUTTER.jpg",
        name:"Bananas & Peanut Butter",
        category:"Night-Cravings",
        description:"Remember how your high school track coach told you to eat bananas to prevent loss That’s because bananas contain potassium, which aids in muscle relaxation",
        price:'₹49',
    }
    
]
export default Menu